### ISSUE TITLE
Codeclimate tries to lint comments?

### ISSUE THREAD

**Issue by frank-borkin** [codeclimate/codeclimate-csslint#11]
Source is here: https://github.com/frank-borkin/ga-pg/blob/master/www/css/index.css
csslint.net (standard options) show no errors, 26 warnings.
Codeclimate shows 5080 issues. (available here: https://codeclimate.com/github/frank-borkin/ga-pg/www/css/index.css - opening this page has another issue, I'll open a seperate bug)
It also shows a churn of 500+ even those this is the only revision of the file.

The first set of errors appear to be where the linter evaluates the contents of comments - it shouldn't.

**Comment by pbrisbin** [comment]
Hi @frank-borkin we had a pretty bad bug in early versions of this engine where it would report the issues in *any* file as present in *all* files. This would lead to seeing issues as reported "on comments" because those are actually issues that are present in some other file in the repo. That was corrected a while ago, but since this repo hasn't seen a commit in 3 months it didn't get an analysis on the fixed version yet.

I've manually triggered one and things seem fixed.

Also note that the Churn numbers and performance problems also seem addressed by getting a good analysis in on the new version.

Sorry for the trouble.
